### ISSUE TITLE
Layout 기본 골격 설정

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/weone#21]
## Summary
레이아웃 기본 작업

## Todo
- [x] 레이아웃 와이어프레임 (Grid)
- [x] 각 컨텐츠 컴포넌트 임시 추가 (Header, Sidebar, Footer, Nav)
- [x] 각 컨텐츠 스타일 기본 세팅 (margin & padding & size 등)
